// components/Navbar.vue
<template>
  <div
    class="fixed flex items-center justify-between w-full px-8 py-4 bg-gray-900"
  >
    <ul class="flex space-x-6">
      <li
        v-for="(item, index) in items"
        :key="index"
        class="transition duration-100 ease-in-out hover:text-gray-400"
        :class="{
          'text-white': $route.path === item.link,
          'text-gray-300': $route.path !== item.link,
        }"
      >
        <nuxt-link :to="item.link.toLowerCase()" class="block">
          {{ item.title }}
        </nuxt-link>
      </li>
    </ul>

    <ul class="flex space-x-6">
      <li class="text-gray-300 hover:text-gray-400">
        <a href="#" target="_blank" class="block">
          <github-icon></github-icon>
        </a>
      </li>
      <li class="text-gray-300 hover:text-gray-400">
        <a href="#" target="_blank" class="block">
          <linkedin-icon></linkedin-icon>
        </a>
      </li>
    </ul>
  </div>
</template>

<script lang="ts" setup>
import GithubIcon from '@/assets/icons/github.svg?component';
import LinkedinIcon from '@/assets/icons/linkedin.svg?component';

interface NavbarItem {
  title: string;
  link: string;
}

const items: NavbarItem[] = [
  { title: 'Blog', link: '/' },
  { title: 'Resume', link: '/resume' },
  { title: 'Contact', link: '/contact' },
  { title: 'Projects', link: '/projects' },
];
</script>

// components/Navbar.tsx
import { NextPage } from 'next';
import { useRouter } from 'next/dist/client/router';
import Link from 'next/link';
import GithubIcon from '../icons/github.svg';
import LinkedinIcon from '../icons/linkedin.svg';

interface NavbarItem {
  title: string;
  link: string;
}

export const Navbar: NextPage = () => {
  const items: NavbarItem[] = [
    { title: 'About', link: '/about' },
    { title: 'Blog', link: '/' },
    { title: 'Resume', link: '/resume' },
    { title: 'Contact', link: '/contact' },
    { title: 'Projects', link: '/projects' },
  ];
  const router = useRouter();

  return (
    <div className="fixed flex items-center justify-between w-full px-8 py-4 bg-gray-900">
      <ul className="flex space-x-6">
        {items.map((item, index) => (
          <li
            key={index}
            className={`transition duration-100 ease-in-out hover:text-gray-400 ${
              router.pathname === item.link ? 'text-white' : 'text-gray-300'
            }`}
          >
            <Link href={item.link} passHref>
              <a className="block">{item.title}</a>
            </Link>
          </li>
        ))}
      </ul>

      <ul className="flex space-x-6">
        <li className="text-gray-300 transition duration-100 ease-in-out hover:text-gray-400">
          <a href="#" target="_blank" className="block">
            <GithubIcon className="w-5 h-5" />
          </a>
        </li>
        <li className="text-gray-300 transition duration-100 ease-in-out hover:text-gray-400">
          <a href="#" target="_blank" className="block">
            <LinkedinIcon className="w-5 h-5" />
          </a>
        </li>
      </ul>
    </div>
  );
};
