// pages/list100.tsx
import { NextPage } from 'next';
import list100 from '../assets/list100.json';

const List100Page: NextPage = (): JSX.Element => {
  return (
    <div className="container max-w-6xl px-8 pt-24 pb-32 mx-auto break-words lg:pt-32 md:px-16">
      <h1 className="mt-4 text-4xl font-bold tracking-tight">
        List 100 - Bucket List
      </h1>

      <p className="mt-10">
        Things I want to do before I die. <i>(Progress as of April 30, 2021)</i>
      </p>

      <ul className="grid grid-cols-1 mt-6 space-y-1 sm:grid-cols-2 sm:gap-4 sm:space-y-0">
        <div className="space-y-1">
          {list100.slice(0, list100.length / 2).map((bucket, index) => (
            <li key={index} className="space-x-2">
              <b
                className={`${bucket.done ? 'text-blue-500' : 'text-red-500'}`}
              >
                {bucket.done ? (
                  <del>{index + 1}</del>
                ) : (
                  <span>{index + 1}</span>
                )}
              </b>
              <span>{bucket.name}</span>
            </li>
          ))}
        </div>
        <div className="space-y-1">
          {list100
            .slice(list100.length / 2, list100.length)
            .map((bucket, index) => (
              <li key={index} className="space-x-2">
                <b
                  className={`${
                    bucket.done ? 'text-blue-500' : 'text-red-500'
                  }`}
                >
                  {bucket.done ? (
                    <del>{index + Math.floor(list100.length / 2) + 1}</del>
                  ) : (
                    <span>{index + Math.floor(list100.length / 2) + 1}</span>
                  )}
                </b>
                <span>{bucket.name}</span>
              </li>
            ))}
        </div>
      </ul>
    </div>
  );
};

export default List100Page;

// src/views/List100.vue
<template>
  <div
    class="
      container
      max-w-4xl
      px-8
      pt-8
      pb-32
      mx-auto
      break-words
      lg:pt-16
      md:px-16
    "
  >
    <h1 class="inline-block text-3xl border-b">List 100 - Bucket List</h1>
    <p class="mt-4">
      Things I want to do before I die. <i>(Progress as of April 30, 2021)</i>
    </p>
    <div
      class="
        grid grid-cols-1
        mt-6
        space-y-2
        sm:gap-4
        sm:grid-cols-3
        sm:space-y-0
      "
    >
      <div v-for="columnIndex in 3" :key="columnIndex" class="space-y-2">
        <p
          v-for="(bucket, index) in list100Data.slice(
            (columnIndex - 1) * Math.ceil(list100Data.length / 3),
            Math.ceil(list100Data.length / 3) * columnIndex,
          )"
          :key="bucket.name"
          class="space-x-2 text-base"
        >
          <span
            class="font-bold text-red-500"
            :class="{ 'text-blue-500': bucket.done }"
          >
            {{
              index +
              1 -
              Math.ceil(list100Data.length / 3) +
              Math.ceil(list100Data.length / 3) * columnIndex
            }}
          </span>
          <del v-if="bucket.done">{{ bucket.name }}</del>
          <span v-else>
            {{ bucket.name }}
          </span>
        </p>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import list100Data from '@/assets/list100.json';

export default defineComponent({
  setup() {
    return {
      list100Data,
    };
  },
});
</script>
