// components/Tag.tsx
import { classes } from '../utils';

import type { JSX } from 'react';

interface TagProps {
  selected: boolean;
  children?: JSX.Element | string;
}

const Tag: React.FC<TagProps> = ({ selected, children }): JSX.Element => {
  const tagClasses = classes(
    {
      'bg-blue-300 text-blue-800': selected,
      'bg-gray-200 text-gray-600': !selected,
    },
    'px-3 py-1 mt-1 mr-1 text-sm rounded-lg cursor-pointer',
  );

  return <div className={tagClasses}>{children}</div>;
};

export default Tag;

// src/components/Tag.vue
<template>
  <div
    class="px-3 py-1 mt-1 mr-1 text-sm bg-gray-200 rounded-lg cursor-pointer"
    :class="{
      'bg-blue-200 text-blue-700': selected,
      'text-gray-600': !selected,
    }"
  >
    <slot />
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
  props: {
    selected: Boolean,
  },
});
</script>
